package com.haodaone.assistant;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class AssistantConversationStoreTest {
    private AssistantConversationStore store;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:assistant-" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", "");
        dataSource.setDriverClassName("org.h2.Driver");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE company (id BIGINT PRIMARY KEY)");
        jdbc.execute("CREATE TABLE app_user (id BIGINT PRIMARY KEY)");
        jdbc.execute("CREATE TABLE employee (id BIGINT PRIMARY KEY)");
        jdbc.execute("CREATE TABLE leave_type (id BIGINT PRIMARY KEY)");
        jdbc.execute("INSERT INTO company (id) VALUES (42)");
        jdbc.execute("INSERT INTO company (id) VALUES (43)");
        jdbc.execute("INSERT INTO app_user (id) VALUES (7)");
        jdbc.execute("INSERT INTO app_user (id) VALUES (8)");
        jdbc.execute("INSERT INTO employee (id) VALUES (51)");
        jdbc.execute("INSERT INTO leave_type (id) VALUES (12)");
        jdbc.execute("""
                CREATE TABLE assistant_conversation (
                    id UUID PRIMARY KEY,
                    company_id BIGINT NOT NULL REFERENCES company(id),
                    user_id BIGINT NOT NULL REFERENCES app_user(id),
                    title VARCHAR(200) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    archived BOOLEAN NOT NULL DEFAULT FALSE
                )
                """);
        jdbc.execute("""
                CREATE TABLE assistant_message (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    conversation_id UUID NOT NULL REFERENCES assistant_conversation(id) ON DELETE CASCADE,
                    sequence_number INTEGER NOT NULL,
                    role VARCHAR(16) NOT NULL,
                    content VARCHAR(8000) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ux_assistant_message_sequence UNIQUE (conversation_id, sequence_number)
                )
                """);
        jdbc.execute("""
                CREATE TABLE assistant_pending_leave_action (
                    conversation_id UUID PRIMARY KEY REFERENCES assistant_conversation(id) ON DELETE CASCADE,
                    company_id BIGINT NOT NULL REFERENCES company(id),
                    user_id BIGINT NOT NULL REFERENCES app_user(id),
                    employee_id BIGINT NOT NULL REFERENCES employee(id),
                    leave_type_id BIGINT REFERENCES leave_type(id),
                    leave_type_name VARCHAR(100),
                    start_date DATE,
                    end_date DATE,
                    reason VARCHAR(500),
                    requested_days DOUBLE PRECISION,
                    remaining_days DOUBLE PRECISION,
                    is_ready BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        store = new AssistantConversationStore(jdbc);
    }

    @Test
    void persistsMessagesAndRestrictsConversationReadsToTenantAndOwner() {
        UUID conversation = store.create(42L, 7L);
        assertThat(store.append(conversation, 42L, 7L, "USER", "How do I apply leave?")).isTrue();
        assertThat(store.append(conversation, 42L, 7L, "ASSISTANT", "Use the Leave page.")).isTrue();

        var snapshot = store.get(conversation, 42L, 7L).orElseThrow();

        assertThat(snapshot.conversation().title()).isEqualTo("How do I apply leave?");
        assertThat(snapshot.messages()).extracting(AssistantConversationStore.StoredMessage::role)
                .containsExactly("USER", "ASSISTANT");
        assertThat(snapshot.messages()).extracting(AssistantConversationStore.StoredMessage::content)
                .containsExactly("How do I apply leave?", "Use the Leave page.");
        assertThat(store.get(conversation, 42L, 8L)).isEmpty();
        assertThat(store.get(conversation, 43L, 7L)).isEmpty();
        assertThat(store.append(conversation, 42L, 8L, "USER", "Not the owner")).isFalse();
        assertThat(store.archive(conversation, 42L, 8L)).isFalse();
        assertThat(store.archive(conversation, 42L, 7L)).isTrue();
        assertThat(store.get(conversation, 42L, 7L)).isEmpty();
        assertThat(store.list(42L, 7L)).isEmpty();
    }

    @Test
    void pendingLeaveProposalIsBoundToItsConversationTenantAndUserAndClearedOnArchive() {
        UUID conversation = store.create(42L, 7L);
        LocalDateTime createdAt = LocalDateTime.of(2026, 10, 9, 12, 34, 56, 123_456_000);
        var proposal = new AssistantConversationStore.PendingLeaveAction(
                51L, 12L, "Casual Leave",
                LocalDate.of(2026, 10, 9), LocalDate.of(2026, 10, 9),
                "Personal appointment", 1.0, 3.0, true, createdAt
        );

        store.savePendingLeave(conversation, 42L, 7L, proposal);

        AssistantConversationStore.PendingLeaveAction stored =
                store.pendingLeave(conversation, 42L, 7L).orElseThrow();
        assertThat(stored.employeeId()).isEqualTo(proposal.employeeId());
        assertThat(stored.leaveTypeId()).isEqualTo(proposal.leaveTypeId());
        assertThat(stored.startDate()).isEqualTo(proposal.startDate());
        assertThat(stored.endDate()).isEqualTo(proposal.endDate());
        assertThat(stored.ready()).isTrue();
        assertThat(stored.createdAt()).isEqualTo(createdAt);
        var locked = store.lockPendingLeave(conversation, 42L, 7L).orElseThrow();
        assertThat(locked.createdAt()).isEqualTo(createdAt);
        assertThat(PendingLeaveExpiry.isExpired(locked.createdAt(), createdAt.plusMinutes(5))).isFalse();
        assertThat(store.pendingLeave(conversation, 43L, 7L)).isEmpty();
        assertThat(store.pendingLeave(conversation, 42L, 8L)).isEmpty();
        assertThat(store.archive(conversation, 42L, 7L)).isTrue();
        assertThat(store.pendingLeave(conversation, 42L, 7L)).isEmpty();
    }
}
