package com.haodaone.assistant;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class AssistantConversationStoreTest {
    private AssistantConversationStore store;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:assistant-" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", "");
        dataSource.setDriverClassName("org.h2.Driver");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE company (id BIGINT PRIMARY KEY)");
        jdbc.execute("CREATE TABLE app_user (id BIGINT PRIMARY KEY)");
        jdbc.execute("INSERT INTO company (id) VALUES (42)");
        jdbc.execute("INSERT INTO company (id) VALUES (43)");
        jdbc.execute("INSERT INTO app_user (id) VALUES (7)");
        jdbc.execute("INSERT INTO app_user (id) VALUES (8)");
        jdbc.execute("""
                CREATE TABLE assistant_conversation (
                    id UUID PRIMARY KEY,
                    company_id BIGINT NOT NULL REFERENCES company(id),
                    user_id BIGINT NOT NULL REFERENCES app_user(id),
                    title VARCHAR(200) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    archived BOOLEAN NOT NULL DEFAULT FALSE
                )
                """);
        jdbc.execute("""
                CREATE TABLE assistant_message (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    conversation_id UUID NOT NULL REFERENCES assistant_conversation(id) ON DELETE CASCADE,
                    sequence_number INTEGER NOT NULL,
                    role VARCHAR(16) NOT NULL,
                    content VARCHAR(8000) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ux_assistant_message_sequence UNIQUE (conversation_id, sequence_number)
                )
                """);
        store = new AssistantConversationStore(jdbc);
    }

    @Test
    void persistsMessagesAndRestrictsConversationReadsToTenantAndOwner() {
        UUID conversation = store.create(42L, 7L);
        assertThat(store.append(conversation, 42L, 7L, "USER", "How do I apply leave?")).isTrue();
        assertThat(store.append(conversation, 42L, 7L, "ASSISTANT", "Use the Leave page.")).isTrue();

        var snapshot = store.get(conversation, 42L, 7L).orElseThrow();

        assertThat(snapshot.conversation().title()).isEqualTo("How do I apply leave?");
        assertThat(snapshot.messages()).extracting(AssistantConversationStore.StoredMessage::role)
                .containsExactly("USER", "ASSISTANT");
        assertThat(snapshot.messages()).extracting(AssistantConversationStore.StoredMessage::content)
                .containsExactly("How do I apply leave?", "Use the Leave page.");
        assertThat(store.get(conversation, 42L, 8L)).isEmpty();
        assertThat(store.get(conversation, 43L, 7L)).isEmpty();
        assertThat(store.append(conversation, 42L, 8L, "USER", "Not the owner")).isFalse();
        assertThat(store.archive(conversation, 42L, 8L)).isFalse();
        assertThat(store.archive(conversation, 42L, 7L)).isTrue();
        assertThat(store.get(conversation, 42L, 7L)).isEmpty();
        assertThat(store.list(42L, 7L)).isEmpty();
    }
}
