package com.haodaone.assistant;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.haodaone.assistant.dto.AssistantChatRequest;
import com.haodaone.attendance.repository.AttendanceRecordRepository;
import com.haodaone.document.service.EmployeeDocumentService;
import com.haodaone.leave.dto.LeaveRequestDTO;
import com.haodaone.leave.service.LeaveRequestService;
import com.haodaone.leave.repository.LeaveTypeRepository;
import com.haodaone.monitoring.service.DeviceEnrollmentService;
import com.haodaone.salary.service.EmployeeSalaryService;
import com.haodaone.security.AuthorizationService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.time.Clock;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import java.util.Set;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

class AssistantLeaveConfirmationFlowTest {
    private static final long COMPANY_ID = 42L;
    private static final long USER_ID = 7L;
    private static final long EMPLOYEE_ID = 51L;
    private static final long LEAVE_TYPE_ID = 12L;
    private static final LocalDate START_DATE = LocalDate.of(2026, 10, 15);
    private static final LocalDate END_DATE = LocalDate.of(2026, 10, 15);
    private static final ZoneId APPLICATION_ZONE = ZoneId.of("Asia/Kolkata");
    private static final Clock CLOCK = Clock.fixed(
            Instant.parse("2026-10-09T11:30:00Z"), APPLICATION_ZONE);

    private JdbcTemplate jdbc;
    private AssistantConversationStore conversationStore;
    private AssistantService assistantService;
    private LeaveRequestService leaveRequestService;
    private AssistantContext context;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:assistant-flow-" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", "");
        dataSource.setDriverClassName("org.h2.Driver");
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE company (id BIGINT PRIMARY KEY)");
        jdbc.execute("CREATE TABLE app_user (id BIGINT PRIMARY KEY)");
        jdbc.execute("CREATE TABLE employee (id BIGINT PRIMARY KEY)");
        jdbc.execute("CREATE TABLE leave_type (id BIGINT PRIMARY KEY)");
        jdbc.execute("INSERT INTO company (id) VALUES (42)");
        jdbc.execute("INSERT INTO app_user (id) VALUES (7)");
        jdbc.execute("INSERT INTO employee (id) VALUES (51)");
        jdbc.execute("INSERT INTO leave_type (id) VALUES (12)");
        jdbc.execute("""
                CREATE TABLE assistant_conversation (
                    id UUID PRIMARY KEY,
                    company_id BIGINT NOT NULL REFERENCES company(id),
                    user_id BIGINT NOT NULL REFERENCES app_user(id),
                    title VARCHAR(200) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    archived BOOLEAN NOT NULL DEFAULT FALSE
                )
                """);
        jdbc.execute("""
                CREATE TABLE assistant_message (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    conversation_id UUID NOT NULL REFERENCES assistant_conversation(id) ON DELETE CASCADE,
                    sequence_number INTEGER NOT NULL,
                    role VARCHAR(16) NOT NULL,
                    content VARCHAR(8000) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ux_assistant_message_sequence UNIQUE (conversation_id, sequence_number)
                )
                """);
        jdbc.execute("""
                CREATE TABLE assistant_pending_leave_action (
                    conversation_id UUID PRIMARY KEY REFERENCES assistant_conversation(id) ON DELETE CASCADE,
                    company_id BIGINT NOT NULL REFERENCES company(id),
                    user_id BIGINT NOT NULL REFERENCES app_user(id),
                    employee_id BIGINT NOT NULL REFERENCES employee(id),
                    leave_type_id BIGINT REFERENCES leave_type(id),
                    leave_type_name VARCHAR(100),
                    start_date DATE,
                    end_date DATE,
                    reason VARCHAR(500),
                    requested_days DOUBLE PRECISION,
                    remaining_days DOUBLE PRECISION,
                    is_ready BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);

        conversationStore = new AssistantConversationStore(jdbc);
        leaveRequestService = mock(LeaveRequestService.class);
        LeaveTypeRepository leaveTypeRepository = mock(LeaveTypeRepository.class);
        com.haodaone.leave.entity.LeaveType leaveType = mock(com.haodaone.leave.entity.LeaveType.class);
        when(leaveType.getId()).thenReturn(LEAVE_TYPE_ID);
        when(leaveType.getName()).thenReturn("Casual Leave");
        when(leaveType.isActive()).thenReturn(true);
        when(leaveTypeRepository.findAllByCompany_IdAndDeletedFalseOrderByNameAsc(COMPANY_ID))
                .thenReturn(List.of(leaveType));
        when(leaveRequestService.preview(any())).thenAnswer(invocation -> {
            var request = invocation.<com.haodaone.leave.dto.ApplyLeaveRequest>getArgument(0);
            assertThat(request.getEmployeeId()).isEqualTo(EMPLOYEE_ID);
            assertThat(request.getLeaveTypeId()).isEqualTo(LEAVE_TYPE_ID);
            assertThat(request.getStartDate()).isEqualTo(START_DATE);
            assertThat(request.getEndDate()).isEqualTo(END_DATE);
            return new LeaveRequestService.LeaveApplicationPreview(
                    EMPLOYEE_ID, LEAVE_TYPE_ID, "Casual Leave", START_DATE, END_DATE, 1.0, 3.0);
        });
        AuthorizationService authorizationService = mock(AuthorizationService.class);
        when(authorizationService.isAllowed("SELF_LEAVE_APPLY", "EMPLOYEE", EMPLOYEE_ID)).thenReturn(true);
        AssistantToolRegistry registry = new AssistantToolRegistry(
                new ObjectMapper(),
                leaveRequestService,
                mock(EmployeeDocumentService.class),
                mock(DeviceEnrollmentService.class),
                mock(AttendanceRecordRepository.class),
                mock(EmployeeSalaryService.class),
                authorizationService,
                leaveTypeRepository,
                conversationStore,
                CLOCK
        );
        AssistantContextResolver contextResolver = mock(AssistantContextResolver.class);
        context = new AssistantContext(USER_ID, EMPLOYEE_ID, COMPANY_ID,
                Set.of("SELF_LEAVE_APPLY"), Set.of("EMPLOYEE"), null, null, null);
        when(contextResolver.resolve()).thenReturn(context);
        assistantService = new AssistantService(
                mock(AiProvider.class), contextResolver, conversationStore, registry, new ObjectMapper(), 3);
    }

    @Test
    void collectingLeaveTypePersistsCompleteReadyProposalBeforeShowingConfirmationAndSubmitsOnConfirmation() {
        UUID conversationId = null;

        var dateResponse = assistantService.chat(new AssistantChatRequest(
                "I want to apply for one day of leave on October 15, 2026.", null, List.of()));
        assertThat(dateResponse.message()).contains("Which leave type");
        assertThat(dateResponse.actions()).isEmpty();
        conversationId = UUID.fromString(dateResponse.conversationId());
        var incompleteDraft = conversationStore.pendingLeave(conversationId, COMPANY_ID, USER_ID).orElseThrow();
        assertThat(incompleteDraft.ready()).isFalse();
        assertThat(incompleteDraft.startDate()).isEqualTo(START_DATE);
        assertThat(incompleteDraft.endDate()).isEqualTo(END_DATE);

        var preparedResponse = assistantService.chat(new AssistantChatRequest(
                "Casual Leave", conversationId.toString(), List.of()));
        assertThat(preparedResponse.conversationId()).isEqualTo(conversationId.toString());
        assertThat(preparedResponse.actions()).hasSize(1);
        assertThat(preparedResponse.actions().getFirst().type()).isEqualTo("LEAVE_CONFIRMATION");
        assertThat(preparedResponse.requiresConfirmation()).isTrue();

        var readyProposal = conversationStore.pendingLeave(conversationId, COMPANY_ID, USER_ID).orElseThrow();
        assertThat(readyProposal.ready()).isTrue();
        assertThat(readyProposal.employeeId()).isEqualTo(EMPLOYEE_ID);
        assertThat(readyProposal.leaveTypeId()).isEqualTo(LEAVE_TYPE_ID);
        assertThat(readyProposal.leaveTypeName()).isEqualTo("Casual Leave");
        assertThat(readyProposal.startDate()).isEqualTo(START_DATE);
        assertThat(readyProposal.endDate()).isEqualTo(END_DATE);
        assertThat(readyProposal.requestedDays()).isEqualTo(1.0);
        assertThat(preparedResponse.actions().getFirst().data())
                .containsEntry("startDate", START_DATE.toString())
                .containsEntry("endDate", END_DATE.toString())
                .containsEntry("days", 1.0);

        LeaveRequestDTO created = mock(LeaveRequestDTO.class);
        when(created.getLeaveTypeName()).thenReturn("Casual Leave");
        when(created.getStartDate()).thenReturn(START_DATE);
        when(created.getEndDate()).thenReturn(END_DATE);
        when(created.getStatus()).thenReturn("PENDING");
        when(created.getId()).thenReturn(876L);
        when(leaveRequestService.apply(any())).thenReturn(created);

        var confirmationResponse = assistantService.chat(new AssistantChatRequest(
                "yes submit", conversationId.toString(), List.of()));

        assertThat(confirmationResponse.message()).contains("has been submitted", "Request ID: 876");
        verify(leaveRequestService).apply(any());
        assertThat(conversationStore.pendingLeave(conversationId, COMPANY_ID, USER_ID)).isEmpty();
    }

    @Test
    void confirmationWithAnotherConversationIdCannotConsumeOrSubmitTheSavedProposal() {
        UUID proposalConversation = conversationStore.create(COMPANY_ID, USER_ID);
        UUID confirmationConversation = conversationStore.create(COMPANY_ID, USER_ID);
        var readyProposal = new AssistantConversationStore.PendingLeaveAction(
                EMPLOYEE_ID, LEAVE_TYPE_ID, "Casual Leave", START_DATE, END_DATE,
                null, 1.0, 3.0, true, java.time.LocalDateTime.now(CLOCK));
        assertThat(conversationStore.savePendingLeave(
                proposalConversation, COMPANY_ID, USER_ID, readyProposal)).isTrue();

        var response = assistantService.chat(new AssistantChatRequest(
                "yes submit", confirmationConversation.toString(), List.of()));

        assertThat(response.message()).contains("There isn't a leave request waiting");
        assertThat(conversationStore.pendingLeave(proposalConversation, COMPANY_ID, USER_ID)).isPresent();
        verifyNoInteractions(leaveRequestService);
    }
}
