ALTER TABLE company ADD COLUMN IF NOT EXISTS industry VARCHAR(100);
ALTER TABLE company ADD COLUMN IF NOT EXISTS company_size VARCHAR(30);
ALTER TABLE company ADD COLUMN IF NOT EXISTS country VARCHAR(100);
ALTER TABLE company ADD COLUMN IF NOT EXISTS workspace_interests TEXT;