CREATE TABLE office_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    company_id BIGINT NOT NULL REFERENCES company(id),
    name VARCHAR(150) NOT NULL,
    address VARCHAR(255),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    allowed_radius_meters INTEGER NOT NULL DEFAULT 150,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_office_location_company_active
    ON office_location(company_id, active);

CREATE INDEX idx_office_location_company_name
    ON office_location(company_id, name);

CREATE TABLE attendance_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    company_id BIGINT NOT NULL REFERENCES company(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    attendance_date DATE NOT NULL,
    check_in_time TIMESTAMP(6) WITHOUT TIME ZONE,
    check_out_time TIMESTAMP(6) WITHOUT TIME ZONE,
    status VARCHAR(30) NOT NULL DEFAULT 'CHECKED_OUT',
    source VARCHAR(30),
    device_id VARCHAR(100),
    location_type VARCHAR(30),
    location_validation_status VARCHAR(40),
    distance_from_office_meters DOUBLE PRECISION,
    office_location_id BIGINT,
    office_location_name VARCHAR(150),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    accuracy_meters DOUBLE PRECISION,
    check_in_source_details VARCHAR(500),
    check_out_source_details VARCHAR(500),
    duration_minutes BIGINT,
    is_wfh BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE wfh_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    company_id BIGINT NOT NULL REFERENCES company(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    work_date DATE NOT NULL,
    reason VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approved_by_employee_id BIGINT REFERENCES employee(id),
    approved_at TIMESTAMP(6) WITHOUT TIME ZONE,
    manager_note VARCHAR(500)
);

CREATE INDEX idx_attendance_session_company_date
    ON attendance_session(company_id, attendance_date);

CREATE INDEX idx_attendance_session_employee_date
    ON attendance_session(employee_id, attendance_date);

CREATE INDEX idx_attendance_session_status
    ON attendance_session(status);

CREATE INDEX idx_wfh_request_company_date
    ON wfh_request(company_id, work_date);

CREATE INDEX idx_wfh_request_employee_status
    ON wfh_request(employee_id, status);
