ALTER TABLE role ADD COLUMN company_id BIGINT REFERENCES company(id);
ALTER TABLE role DROP CONSTRAINT IF EXISTS role_name_key;
CREATE UNIQUE INDEX IF NOT EXISTS ux_role_name_company ON role (name, company_id);

CREATE TABLE role_permission_scope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES role(id),
    permission_id BIGINT NOT NULL REFERENCES permission(id),
    scope VARCHAR(20) NOT NULL,
    valid_from TIMESTAMP(6) WITHOUT TIME ZONE,
    valid_until TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uk_role_permission_scope UNIQUE (role_id, permission_id),
    CONSTRAINT ck_role_permission_scope_value CHECK (scope IN ('SELF', 'TEAM', 'DEPARTMENT', 'ORGANIZATION', 'CUSTOM'))
);
CREATE INDEX ix_role_permission_scope_role ON role_permission_scope(role_id);
CREATE INDEX ix_role_permission_scope_permission ON role_permission_scope(permission_id);
