ALTER TABLE subscription
    ADD COLUMN IF NOT EXISTS billing_cycle VARCHAR(20),
    ADD COLUMN IF NOT EXISTS billable_employee_count INTEGER;

CREATE TABLE IF NOT EXISTS payment_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    company_id BIGINT NOT NULL REFERENCES company(id),
    subscription_id BIGINT REFERENCES subscription(id),
    plan VARCHAR(50) NOT NULL,
    razorpay_order_id VARCHAR(100) NOT NULL,
    razorpay_payment_id VARCHAR(100),
    razorpay_signature VARCHAR(255),
    currency VARCHAR(20) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    payment_method VARCHAR(50),
    paid_at TIMESTAMP(6) WITHOUT TIME ZONE,
    webhook_event VARCHAR(100)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_transaction_razorpay_order
    ON payment_transaction(razorpay_order_id)
    WHERE razorpay_order_id IS NOT NULL AND deleted = FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS uk_payment_transaction_razorpay_payment
    ON payment_transaction(razorpay_payment_id)
    WHERE razorpay_payment_id IS NOT NULL AND deleted = FALSE;

CREATE INDEX IF NOT EXISTS ix_payment_transaction_company ON payment_transaction(company_id);
CREATE INDEX IF NOT EXISTS ix_payment_transaction_subscription ON payment_transaction(subscription_id);
CREATE INDEX IF NOT EXISTS ix_payment_transaction_status ON payment_transaction(status);
