ALTER TABLE company
    ADD COLUMN IF NOT EXISTS legal_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS billing_address VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS gstin VARCHAR(30);

CREATE SEQUENCE IF NOT EXISTS billing_invoice_number_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS billing_invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    invoice_number VARCHAR(40) NOT NULL,
    company_id BIGINT NOT NULL REFERENCES company(id),
    subscription_id BIGINT REFERENCES subscription(id),
    payment_transaction_id BIGINT NOT NULL REFERENCES payment_transaction(id),
    invoice_type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    invoice_date DATE NOT NULL,
    billing_period_start DATE,
    billing_period_end DATE,
    plan VARCHAR(50),
    employee_count INTEGER,
    billing_cycle VARCHAR(20),
    unit_rate NUMERIC(12,2),
    subtotal NUMERIC(12,2) NOT NULL,
    discount NUMERIC(12,2) NOT NULL DEFAULT 0,
    tax NUMERIC(12,2) NOT NULL DEFAULT 0,
    total NUMERIC(12,2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    payment_method VARCHAR(50),
    razorpay_order_id VARCHAR(100),
    razorpay_payment_id VARCHAR(100),
    email_status VARCHAR(20) NOT NULL DEFAULT 'NOT_SENT'
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_billing_invoice_number ON billing_invoice(invoice_number);
CREATE UNIQUE INDEX IF NOT EXISTS uk_billing_invoice_payment ON billing_invoice(payment_transaction_id);
CREATE INDEX IF NOT EXISTS ix_billing_invoice_company_date ON billing_invoice(company_id, invoice_date DESC);
CREATE INDEX IF NOT EXISTS ix_billing_invoice_status ON billing_invoice(company_id, status);
