CREATE TABLE user_permission_grant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    company_id BIGINT NOT NULL REFERENCES company(id),
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    permission_id BIGINT NOT NULL REFERENCES permission(id),
    scope VARCHAR(20) NOT NULL,
    granted_by_user_id BIGINT NOT NULL REFERENCES app_user(id),
    granted_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_by_user_id BIGINT REFERENCES app_user(id),
    revoked_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT ck_user_permission_grant_scope
        CHECK (scope IN ('SELF', 'TEAM', 'DEPARTMENT', 'ORGANIZATION', 'CUSTOM')),
    CONSTRAINT ck_user_permission_grant_revocation
        CHECK ((revoked_at IS NULL AND revoked_by_user_id IS NULL)
            OR (revoked_at IS NOT NULL AND revoked_by_user_id IS NOT NULL))
);

CREATE INDEX ix_user_permission_grant_company_user
    ON user_permission_grant (company_id, user_id, granted_at DESC);

CREATE INDEX ix_user_permission_grant_permission
    ON user_permission_grant (permission_id);

CREATE INDEX ix_user_permission_grant_granted_by
    ON user_permission_grant (granted_by_user_id);

CREATE UNIQUE INDEX ux_user_permission_grant_active
    ON user_permission_grant (company_id, user_id, permission_id)
    WHERE revoked_at IS NULL AND deleted = FALSE;
