ALTER TABLE company
    ADD COLUMN attendance_method VARCHAR(20) NOT NULL DEFAULT 'HYBRID',
    ADD COLUMN manual_regularization_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN regularization_approval_required BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN attendance_grace_minutes INTEGER NOT NULL DEFAULT 10;

ALTER TABLE employee
    ADD COLUMN attendance_method_override VARCHAR(20),
    ADD COLUMN biometric_device_id BIGINT REFERENCES biometric_device(id);

CREATE INDEX idx_employee_biometric_device
    ON employee(biometric_device_id);

ALTER TABLE attendance_record
    ADD COLUMN source VARCHAR(30) NOT NULL DEFAULT 'BIOMETRIC';

CREATE TABLE attendance_regularization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    company_id BIGINT NOT NULL REFERENCES company(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    attendance_date DATE NOT NULL,
    requested_check_in TIME WITHOUT TIME ZONE NOT NULL,
    requested_check_out TIME WITHOUT TIME ZONE,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    reviewed_by_employee_id BIGINT REFERENCES employee(id),
    reviewed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    review_note VARCHAR(500)
);

CREATE INDEX idx_attendance_regularization_company_status
    ON attendance_regularization(company_id, status, attendance_date);

CREATE INDEX idx_attendance_regularization_employee_date
    ON attendance_regularization(employee_id, attendance_date);
