ALTER TABLE notification
    ADD COLUMN deduplication_key VARCHAR(255);

CREATE UNIQUE INDEX ux_notification_recipient_deduplication
    ON notification (company_id, recipient_user_id, deduplication_key)
    WHERE deduplication_key IS NOT NULL;

CREATE TABLE notification_email_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    company_id BIGINT NOT NULL REFERENCES company(id),
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    workflow_email_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ux_notification_email_preference_user_company UNIQUE (company_id, user_id)
);

CREATE INDEX ix_notification_company_recipient_created
    ON notification (company_id, recipient_user_id, created_at DESC)
    WHERE deleted = FALSE;
