CREATE TABLE assistant_conversation (
    id UUID PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES company(id),
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    title VARCHAR(200) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX ix_assistant_conversation_owner_updated
    ON assistant_conversation (company_id, user_id, updated_at DESC)
    WHERE archived = FALSE;

CREATE TABLE assistant_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id UUID NOT NULL REFERENCES assistant_conversation(id) ON DELETE CASCADE,
    sequence_number INTEGER NOT NULL,
    role VARCHAR(16) NOT NULL CHECK (role IN ('USER', 'ASSISTANT')),
    content VARCHAR(8000) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_assistant_message_sequence UNIQUE (conversation_id, sequence_number)
);

CREATE INDEX ix_assistant_message_conversation_sequence
    ON assistant_message (conversation_id, sequence_number DESC);
