CREATE TABLE employee_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100), updated_by VARCHAR(100), deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    company_id BIGINT NOT NULL REFERENCES company(id),
    employee_id BIGINT NOT NULL REFERENCES employee(id),
    asset_type VARCHAR(80) NOT NULL,
    asset_tag VARCHAR(120),
    description VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'ASSIGNED',
    assigned_at DATE,
    returned_at DATE,
    notes VARCHAR(1000)
);

CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100), updated_by VARCHAR(100), deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    company_id BIGINT NOT NULL REFERENCES company(id),
    recipient_user_id BIGINT NOT NULL REFERENCES app_user(id),
    type VARCHAR(40) NOT NULL DEFAULT 'GENERAL',
    title VARCHAR(200) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    entity_type VARCHAR(80), entity_id BIGINT,
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    read_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE support_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100), updated_by VARCHAR(100), deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP(6) WITHOUT TIME ZONE,
    company_id BIGINT NOT NULL REFERENCES company(id),
    requester_employee_id BIGINT NOT NULL REFERENCES employee(id),
    category VARCHAR(50) NOT NULL DEFAULT 'GENERAL',
    subject VARCHAR(200) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    resolution_note VARCHAR(2000), closed_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE INDEX idx_employee_asset_self ON employee_asset(company_id, employee_id, deleted);
CREATE INDEX idx_notification_recipient ON notification(company_id, recipient_user_id, read_at, deleted);
CREATE INDEX idx_support_request_owner ON support_request(company_id, requester_employee_id, deleted);
